### ISSUE TITLE
Process not exiting

### ISSUE THREAD

**Issue by shiftgeist** [windicss/postcss-windicss#1]
From my understanding the process of windicss keeps running when it detects NODE_ENV in dev mode. However this is disadvantageous when working with Hugo. Since it waits for postcss to finish but never gets the signal. (Hugo come with its own file system watcher).

One idea of mine was to use the watcher that postcss includes, than it would be decided from outside if the process continues. Another idea I had is to pass a watch option to postcss-windicss.

Hugo uses the environment variable `HUGO_ENVIRONMENT` ([read more here](https://gohugo.io/hugo-pipes/postcss/#check-hugo-environment-from-postcssconfigjs))

---

A workaround from https://github.com/windicss/windicss/issues/184:

> [...] For now, the postcss plugin checks `process.env.NODE_ENV` to aware of the mode (dev for continuous serve, and build for one-time). So, my assumption here is that it mis-detected as dev environment and that could be the why the process does not exit.
>
> As a workaround for now, is to specify the env by `cross-env NODE_ENV=production npm run build`

example postcss.config.js

```js
process.env.NODE_ENV = 'production'

module.exports = {
    plugins: [
        require('postcss-import')({
            path: ['assets/css'],
        }),
        require('postcss-windicss')({
            config: './assets/css/tailwind.config.js',
            scan: {
                dirs: ['./layouts/', './content/'],
            },
        })
    ],
}
```

**Comment by deleonio** [comment]
Maybe related to: https://github.com/windicss/postcss-windicss/issues/3 and https://github.com/windicss/postcss-windicss/issues/5

**Comment by deleonio** [comment]
@shiftgeist can you retry it with v0.1? Thx

**Comment by shiftgeist** [comment]
v0.1 seems to be working
