### ISSUE TITLE
Implementation of `import 'virtual:windi-devtools'` in postcss

### ISSUE THREAD

**Issue by shiftgeist** [windicss/postcss-windicss#10]
Is it possible to https://windicss.org/guide/vite.html#design-in-devtools with postcss?

**Comment by antfu** [comment]
Not sure, but maybe you can give it a try. Or try https://github.com/antfu/windicss-runtime-dom.

That said, I'd still recommend to use other integrations to get the best overall support and treat this plugin as your last option.

**Comment by shiftgeist** [comment]
The issue was chokidar, which watched the wrong (?) dirs. When setting the `include` dirs in the postcss plugin configuration it updates the styling.

I still might look into this.

<details>
  <summary>My config for Hugo</summary>
 
```js
// assets/css/postcss.config.js

const production = process.env.HUGO_ENVIRONMENT === 'production'
process.env.NODE_ENV = 'production' // disable watch mode

module.exports = {
    plugins: [
        require('postcss-import')({
            path: ['assets/css'],
        }),
        require('postcss-windicss')({
            config: './assets/css/tailwind.config.js',
            safelist: [],
            scan: {
                include: ['layouts/**/*'],
            },
        }),
        ...(production ? [require('postcss-csso')] : []),
    ],
}
```

</details>
