### ISSUE TITLE
Style does not change in watch mode

### ISSUE THREAD

**Issue by deleonio** [windicss/postcss-windicss#3]
If I change the style during development (watch), it won't be adopted.

Here is a repo to reproduce.: https://github.com/deleonio/stencil-meets-windicss

**Comment by antfu** [comment]
Does it compare the content? The current approach touches the css file (bump `mtime`) but does not changes the file.

Or does it works with tailwind jit? (it's similar approach I think)

**Comment by deleonio** [comment]
It doesn't work with tailwind jit either (https://github.com/tailwindlabs/tailwindcss-jit/issues/126).

I only had changed the tsx file.

**Comment by deleonio** [comment]
Here are some things you can find helpful:

- If I change a css class in `TSX` file nothing happens.
- If I resave the `CSS` file it update the style.

**The update on changes in the code only responds to the saving of CSS-Files.**

**Comment by antfu** [comment]
Wondering what's `stencil` built on under the hood, snowpack, or a complete custom one?

**Comment by antfu** [comment]
> If I resave the CSS file it update the style.

Do you make any changes to the CSS file or just a plain `Ctrl+S` will do?

**Comment by deleonio** [comment]
Hi @antfu,

I need to make some changes in the CSS file to trigger the recompile. **I think thats right. But we have to compile by changing other files as well.**

**Comment by deleonio** [comment]
I will check the `plugin context includes`, today.
