### ISSUE TITLE
Watcher close not correctly

### ISSUE THREAD

**Issue by deleonio** [windicss/postcss-windicss#5]
I analyse the change detection issue and see more and more logs. Also logs from watcher I have removed. So I think, the watcher Callbacks are alive.

`Ctrl` + `c` does not cancel the watcher.

![image](https://user-images.githubusercontent.com/6279703/113864322-0ee4a780-97ab-11eb-9781-f1d947e73282.png)

**Comment by deleonio** [comment]
i solved it with `exit-hook` - PR next...

**Comment by deleonio** [comment]
@antfu I like you refactoring - first I had also separate function - is clean code. but the diff was minimal.

PS: switch is much faster then if-then-else by more cases:
- https://www.measurethat.net/Benchmarks/Show/3086/0/switch-vs-if#latest_results_block
- https://jsben.ch/5w6eT

Thank you for this challenge - next I will publish windi integration in our latest @leanupjs (v1.2, v1.1 and v1.0) releases.

**Comment by antfu** [comment]
Thanks for the info. But I kinda think it's the case when we have multiple conditions for the switch to be faster. When we have more options, we can switch to `switch` for sure. But either way would not be the bottleneck at all (fs has a different level of overhead after all).

Looking forward to @leanupjs. 🙌
